- .github/workflows/build.yml
- .github/workflows/docs-build.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/docs-release-tag.yml
- .github/workflows/docs-release.yml
- .github/workflows/gold-data-report.yml
- .github/workflows/gold-data-script-validation.yml
- .github/workflows/release.yml
- .github/workflows/spark-tests-internal.yml
- .github/workflows/spark-tests.yml
- docs/.vitepress/config.mts
- docs/.vitepress/theme/components/PageList.vue
- docs/.vitepress/theme/utils/sphinx.ts
- docs/.vitepress/theme/utils/tree.ts
- package.json
- pyproject.toml
- tsconfig.json
1. Add documentation workflows.
2. Rename a few existing workflows.
> Add documentation workflows

- README.md
- docs/.vitepress/config.mts
- docs/.vitepress/theme/layouts/MainLayout.vue
1. Update README.
2. Update `robots` `<meta>` tag.
3. Update docs site configuration.
> Update README for the docs site launch

- crates/sail-plan/src/resolver/data_source.rs
- crates/sail-python/src/spark/server.rs
- docs/guide/getting-started/index.md
- docs/guide/tasks/data-access.md
- docs/guide/tasks/index.data.ts
- docs/guide/tasks/index.md
- python/pysail/spark/__init__.py
- python/pysail/spark/__main__.py
1. Add object store documentation.
2. Update Python API.
> Add object store docs

- docs/.vitepress/config.mts
- docs/guide/getting-started/index.md
- docs/index.md
- docs/reference/python/[page].md
- docs/reference/python/[page].paths.ts
- tsconfig.json
1. Support dynamic meta tags in documentation pages.
2. Update the Getting Started guide.
> Support dynamic meta tags in docs

- docs/.vitepress/config.mts
- docs/.vitepress/theme/layouts/MainLayout.vue
We would like search engines to index dev guide from the `main` branch.
> Update robots meta tag for docs

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- crates/sail-common/Cargo.toml
- crates/sail-plan/Cargo.toml
- crates/sail-python-udf/Cargo.toml
- crates/sail-python/Cargo.toml
- crates/sail-python/src/lib.rs
- crates/sail-spark-connect/Cargo.toml
- crates/sail-sql/Cargo.toml
- crates/sail-telemetry/Cargo.toml
- docs/.vitepress/config.mts
- docs/development/release/index.md
- docs/reference/changelog/index.md
- docs/reference/index.md
- pyproject.toml
- python/pysail/__init__.py
- python/pysail/tests/test_package.py
1. Change the project version to 0.1.1.
2. Update the release process for Test PyPI. The tags `test/v*` are no longer in use.
3. Add changelog in the documentation.
> Prepare 0.1.1 release

- .gitignore
- crates/sail-common/src/spec/expression.rs
- crates/sail-plan/src/catalog/table.rs
- crates/sail-plan/src/config.rs
- crates/sail-plan/src/resolver/plan.rs
- scripts/spark-tests/wait-for-server.sh
After this PR, I'm able to write to table in my manual testing. But I cannot add unit tests for this since `DROP TABLE` does not fully work yet. (The data is not deleted when the table is dropped.)
More work is needed in future PRs. I've added TODO comments in various places.
> Fix `INSERT INTO` statement

- crates/sail-execution/src/driver/actor/core.rs
- crates/sail-execution/src/driver/actor/handler.rs
- crates/sail-execution/src/driver/event.rs
- crates/sail-execution/src/driver/server.rs
- crates/sail-execution/src/driver/state.rs
- crates/sail-execution/src/job/runner.rs
- crates/sail-execution/src/worker/actor/core.rs
- crates/sail-execution/src/worker/actor/handler.rs
- crates/sail-execution/src/worker/event.rs
- crates/sail-execution/src/worker/flight_server.rs
- crates/sail-execution/src/worker/server.rs
- crates/sail-server/src/actor.rs
This PR changes the signature of a few actor methods to enforce error handling inside actor message handlers and actor-spawned tasks.
> Improve actor error handling

- crates/sail-execution/src/driver/actor/core.rs
- crates/sail-execution/src/driver/actor/handler.rs
- crates/sail-execution/src/driver/event.rs
- crates/sail-execution/src/driver/state.rs
- crates/sail-execution/src/job/runner.rs
- crates/sail-execution/src/worker_manager/local.rs
- crates/sail-execution/src/worker_manager/mod.rs
- crates/sail-server/src/actor.rs
1. Implement `ActorSystem` to keep track of the actor event loop.
2. Improve the `WorkerManager` trait.
> Implement actor system

- Cargo.lock
- crates/sail-plan/Cargo.toml
- crates/sail-plan/src/function/mod.rs
- crates/sail-plan/src/function/table/mod.rs
- crates/sail-plan/src/function/table/range.rs
- crates/sail-plan/src/lib.rs
- crates/sail-plan/src/literal.rs
- crates/sail-plan/src/resolver/plan.rs
- crates/sail-spark-connect/tests/gold_data/function/generator.json
- crates/sail-spark-connect/tests/gold_data/plan/plan_select.json
- crates/sail-sql/src/parser.rs
- python/pysail/tests/spark/test_table_function.py
1. Support `range`, `explode`, and `posexplode` in the SQL `FROM` clause.
2. Support SQL parsing for the `TABLE` argument in UDTF.
> Support SQL table function

- crates/sail-plan/src/resolver/plan.rs
- python/pysail/tests/spark/test_tpcds.py
1. Support window function after aggregation.
2. Fix an issue with sort order rebase for aliased aggregation expressions.
> Support more TPC-DS queries

- README.md
- crates/sail-common/src/spec/expression.rs
- crates/sail-plan/src/resolver/expression.rs
- crates/sail-spark-connect/src/proto/expression.rs
- docs/.vitepress/config.mts
- docs/.vitepress/theme/app.css
- docs/.vitepress/theme/components/PySparkApi.vue
- docs/.vitepress/theme/languages/pycon.ts
- docs/.vitepress/theme/layouts/MainLayout.vue
- docs/guide/tasks/udf/examples.md
- docs/guide/tasks/udf/index.data.ts
- docs/guide/tasks/udf/index.md
- docs/guide/tasks/udf/overview.md
- pyproject.toml
- python/pysail/tests/spark/conftest.py
- python/pysail/tests/spark/udf/test_arrow_map_udf.txt
- python/pysail/tests/spark/udf/test_pandas_agg_udf.txt
- python/pysail/tests/spark/udf/test_pandas_grouped_map_udf.txt
- python/pysail/tests/spark/udf/test_pandas_map_udf.txt
- python/pysail/tests/spark/udf/test_pandas_scalar_udf.txt
- python/pysail/tests/spark/udf/test_register_scalar_udf.txt
- python/pysail/tests/spark/udf/test_register_udtf.txt
- python/pysail/tests/spark/udf/test_scalar_udf.txt
- python/pysail/tests/spark/udf/test_udtf.txt
1. Update README.
2. Add UDF documentation and add examples that can be verified as doctests in pytest.
3. Support `call_function`.
> Add UDF docs and update README

- crates/sail-spark-connect/tests/gold_data/plan/plan_join.json
- crates/sail-spark-connect/tests/gold_data/plan/plan_select.json
- crates/sail-spark-connect/tests/gold_data/plan/unpivot_join.json
- crates/sail-spark-connect/tests/gold_data/plan/unpivot_select.json
- crates/sail-sql-analyzer/src/query.rs
- crates/sail-sql-parser/src/ast/data_type.rs
- crates/sail-sql-parser/src/ast/expression.rs
- crates/sail-sql-parser/src/ast/query.rs
- crates/sail-sql-parser/src/ast/statement.rs
- crates/sail-sql-parser/src/parser.rs
This PR adds support for queries with nested table factors in the `FROM` clause.
> Support more SQL syntax

- crates/sail-plan/src/resolver/expression.rs
- crates/sail-plan/src/resolver/plan.rs
- crates/sail-plan/src/resolver/schema.rs
- crates/sail-plan/src/resolver/state.rs
- python/pysail/tests/spark/conftest.py
- python/pysail/tests/spark/test_join.txt
1. Support natural join.
2. Skip hidden fields in wildcard expansion.
> Support natural join

- docs/development/spark-tests/spark-setup.md
Hi
Update doc to set tag in Spark repository #523 
if it is not necessary to close the PR, thank you
> Docs set tag in Spark to test

- crates/sail-plan/src/function/aggregate.rs
- crates/sail-spark-connect/tests/gold_data/function/agg.json
count_if function implementation
https://spark.apache.org/docs/latest/api/sql/index.html#count_if
```
> SELECT count_if(col % 2 = 0) FROM VALUES (NULL), (0), (1), (2), (3) AS tab(col);
2
> SELECT count_if(col IS NULL) FROM VALUES (NULL), (0), (1), (2), (3) AS tab(col);
1
```
passes doctests, no caveats found yet
part of #309
> feat: count_if function

- crates/sail-common/src/spec/plan.rs
- crates/sail-plan/src/catalog/mod.rs
- crates/sail-plan/src/catalog/table.rs
- crates/sail-plan/src/catalog/view.rs
- crates/sail-plan/src/extension/logical/catalog.rs
- crates/sail-plan/src/resolver/plan.rs
- crates/sail-spark-connect/src/session_manager.rs
- crates/sail-spark-connect/tests/gold_data/plan/ddl_show_views.json
- crates/sail-sql-analyzer/src/statement.rs
- docs/guide/sql/features.md
I've tested the changes locally but we could add some tests in the future once we have better setup around catalog features.
> feat: support SQL `SHOW` statements

- crates/sail-python-udf/src/python/spark.py
now no rows with are produced for empty partitions:
```python
from pyspark.sql import SparkSession, Row
from pyspark.sql.functions import udtf, lit
server.start()
@udtf(returnType="key: string, value: float")
class TestUDTF:
def __init__(self):
self._count = 0
self._sum = 0
def eval(self, x: int):
self._count += 1
self._sum += x
yield "input", float(x)
def terminate(self):
yield "count", float(self._count)
yield "sum", float(self._sum)
spark.udtf.register("test_udtf", TestUDTF)
df = spark.sql(
"""SELECT id, key, value FROM range(0, 0, 1, 2), …
```
> fix: pysparktableudf behaviour on empty partitions with no recordbatches

- crates/sail-plan/src/resolver/expression.rs
move cast rename resolving fully to the resolve_expression_cast level
change renaming logic:
rename cast to `CAST expr as TYPE` in all cases except:
1) expr is a column
2) expr is aliased
3) expr is a cast or a try_cast, and the arg coerces eventually to 1) or 2)
this cases maintain the inner naming 
old rename variable values are not used, but saved just in case
closes #684
> fix: cast expr renaming

- crates/sail-plan/src/function/aggregate.rs
avg now returns NULL on NullType input, like spark does
```python
server.start()
#spark = SparkSession.builder.appName("test").master("local[1]").getOrCreate()
import pyspark.sql.functions as sf
df = spark.sql("SELECT * FROM VALUES (null) AS tab(y)")
df.select(sf.avg("y")).show()
```
```
+------+
|avg(y)|
+------+
|  NULL|
+------+
```
closes #700
> fix: avg func exception on NullType input

- crates/sail-plan/src/extension/function/kurtosis.rs
- crates/sail-plan/src/extension/function/skewness.rs
skewness and kurtosis functions written from scratch using algorithms like in spark:
- skewness:
https://github.com/apache/spark/blob/d3f2054fa0ef9d062a5f451648e085efc0f94896/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CentralMomentAgg.scala#L293
- kurtosis:
https://github.com/apache/spark/blob/d3f2054fa0ef9d062a5f451648e085efc0f94896/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CentralMomentAgg.scala#L324
- they share this common logic:
https://github.com/apache/spark/blob/4693e09f4affff109fab0cd6e4ccec30705d1534/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CentralMomentAgg.scala#L49
kurtosis code reuses most of the skewness codebase
skewness passes spark-tests
kurtosis doesn't pass …
> fix: skewness and kurtosis funcs

- crates/sail-plan/src/function/scalar/math.rs
now logarithm functions return NULL if the input is incorrect in terms of math definitions
log2 does not pass spark-tests due to show() formatting, there is an additional space in spark output
closes #733 
part of #506
> fix: logarithm funcs results on non-positive input

- README.md
> chore: add url codecov in README

- Cargo.lock
- Cargo.toml
- crates/sail-plan/Cargo.toml
- crates/sail-plan/src/resolver/query/column_op.rs
> fix: deterministic schema for `withColumns`

- crates/sail-plan/src/extension/function/math/spark_try_mult.rs
`try_multiply` fix and refactoring
more supportive for interval and i64 arg types combinations
now passes spark-tests
some code deduplication
part of #506
> fix: try_multiply function

- Cargo.lock
- crates/sail-data-source/build.rs
- crates/sail-data-source/src/formats/binary/file_format.rs
- crates/sail-data-source/src/formats/binary/mod.rs
- crates/sail-data-source/src/formats/binary/options.rs
- crates/sail-data-source/src/formats/binary/reader.rs
- crates/sail-data-source/src/formats/binary/source.rs
- crates/sail-data-source/src/formats/mod.rs
- crates/sail-data-source/src/formats/text/source.rs
- crates/sail-data-source/src/options/data/binary_read.yaml
- crates/sail-data-source/src/options/mod.rs
- crates/sail-data-source/src/registry.rs
- crates/sail-execution/proto/sail/plan/physical.proto
- crates/sail-execution/src/codec.rs
- docs/guide/formats/index.md
- docs/introduction/getting-started/index.md
- pyproject.toml
- python/pysail/tests/spark/test_datasources.py
> feat: binary file reader

- .github/workflows/claude.yml
The price is the same.
<https://aws.amazon.com/bedrock/pricing/>
> chore: use Claude Sonnet 4 for Claude Code

- docs/introduction/index.md
- added the word "multimodal" to be consistent with messaging across website and future README.
> docs: introduction (added word "multimodal")

- crates/sail-plan/src/formatter.rs
- crates/sail-plan/src/resolver/query/sort.rs
- python/pysail/tests/spark/test_order_by_aggregate.txt
> fix: sorting by aggregate expressions
