lakehq/sail

.github/workflows/docs-build.yml
docs/.vitepress/config.mts
eslint.config.js
tsconfig.json

We would like to prevent search engines from indexing the documentation site for the `main` branch. A `<meta>` tag can be added for this purpose.
According to the [reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name), this is recommended even if we have `robots.txt` to prevent crawling:
> The `robots` `<meta>` tag and `robots.txt` file serve different purposes: `robots.txt` controls the crawling of pages, and does not affect indexing or other behavior controlled by `robots` meta. A page that can't be crawled may still be indexed if it is referenced by another document.

Add robots meta tag in docs

---

crates/sail-python-udf/src/cereal/mod.rs
crates/sail-python-udf/src/cereal/pyspark_udf.rs
crates/sail-python-udf/src/cereal/pyspark_udtf.rs
crates/sail-python-udf/src/error.rs
crates/sail-python-udf/src/lib.rs
crates/sail-python-udf/src/udf/mod.rs
crates/sail-python-udf/src/udf/pyspark_udf.rs
crates/sail-python-udf/src/udf/pyspark_udtf.rs

This removes the nearly 100 lines of `.map_err(|e| DataFusionError::External(e.into()))` in the Python UDF crate.

Define error type for Python UDF

---

.github/actions/pull-request-report/action.yml
.github/workflows/build.yml
.github/workflows/gold-data.yml
.github/workflows/report.yml
.github/workflows/spark-tests.yml

Workflows triggered by fork repo pull requests can only use GitHub read tokens. (A write token for public repo pull requests would result in security vulnerability.) Therefore, publishing reports as PR comments fails due to lack of permissions.
This PR adds a workflow to publish PR comments on `workflow_run` events (rather than `pull_request` events). In this way, the write token can be used to update the PR with comments.

Publish PR comments in a separate workflow

---

crates/sail-common/src/config/application.rs
crates/sail-common/src/config/default.toml
crates/sail-execution/src/driver/actor/core.rs
crates/sail-execution/src/driver/actor/handler.rs
crates/sail-execution/src/driver/event.rs
crates/sail-execution/src/driver/state.rs
crates/sail-execution/src/job/runner.rs
crates/sail-execution/src/worker/actor/core.rs
crates/sail-server/src/actor.rs
crates/sail-spark-connect/src/error.rs
crates/sail-spark-connect/src/proto/function.rs
crates/sail-spark-connect/src/server.rs
crates/sail-spark-connect/src/session.rs
crates/sail-spark-connect/src/session_manager.rs

1. Support removing idle Spark sessions.
2. Switch to a more robust approach for timeout event handling in all actors.

Support removing idle Spark sessions

---

.github/actions/adjust-swap-space/action.yml

It seems we need even more swap space in a fresh build.

Increase swap size in build

---

.github/actions/setup-rust/action.yml
crates/sail-sql-analyzer/src/literal.rs

Cache thrashing happens more frequently due to increase in Rust cache size (2.7 GB) and the limited cache storage (10 GB per repository). This PR mitigates the issue by avoid saving caches from pull requests.

Improve cache usage in GitHub Actions

---

crates/sail-spark-connect/tests/gold_data/expression/interval.json
crates/sail-spark-connect/tests/gold_data/expression/misc.json
crates/sail-spark-connect/tests/gold_data/expression/numeric.json
crates/sail-spark-connect/tests/gold_data/expression/string.json
crates/sail-spark-connect/tests/gold_data/plan/ddl_create_table.json
crates/sail-spark-connect/tests/gold_data/plan/ddl_replace_table.json
crates/sail-spark-connect/tests/gold_data/plan/plan_select.json
crates/sail-sql-analyzer/src/expression.rs
crates/sail-sql-analyzer/src/literal.rs
crates/sail-sql-analyzer/src/statement.rs
crates/sail-sql-analyzer/src/value.rs
crates/sail-sql-parser/src/ast/expression.rs
crates/sail-sql-parser/src/ast/identifier.rs
crates/sail-sql-parser/src/ast/literal.rs
crates/sail-sql-parser/src/lexer.rs
crates/sail-sql-parser/src/token.rs

1. Support identifiers starting with a digit. The solution is to remove `Token::Number` from the lexer. Whether an unquoted word is parsed as a number literal or an identifier is now decided in the parser, depending on the context. When we used `sqlparser-rs`, this was only partially supported in `CREATE TABLE` statements since we did not have full control over tokenization.
2. Support concatenating multiple string literals into one literal expression.

Support more SQL syntax

---

.github/actions/setup-rust/action.yml

We started getting the following error in GitHub Actions for Rust setup. This PR tries to fix the issue.
```text
error: invalid value 'clippy' for '[TOOLCHAIN]...': invalid toolchain name: 'clippy'
```

Fix rustup clippy installation issue

---

Cargo.lock
Cargo.toml
crates/sail-plan/Cargo.toml
crates/sail-plan/src/object_store/hugging_face.rs
crates/sail-plan/src/object_store/mod.rs
crates/sail-plan/src/object_store/registry.rs
docs/guide/tasks/data-access.md

This PR implements the Hugging Face object store so that we can load datasets via the `hf://` protocol.
I used the official `hf-hub` library to make HTTP requests to the Hugging Face Hub. Compared with other implementations (e.g. OpenDAL), the `hf-hub` library has a nice feature that the downloaded files are kept in a local cache. The local cache is compatible with the cache used by the Hugging Face Python library. This avoids unnecessary download operations and allows for cache sharing among Sail and other Hugging Face Python tools.

Implement Hugging Face object store

---

crates/sail-spark-connect/tests/gold_data/expression/numeric.json
crates/sail-sql-analyzer/src/expression.rs
crates/sail-sql-analyzer/src/literal.rs
crates/sail-sql-analyzer/src/value.rs

This PR removes the `LiteralValue` struct and various `TryFrom` trait implementation. The logic is now written in functions. This makes literal parsing logic in the SQL analyzer easier to understand.

Clean up literal value parser

---

Cargo.lock
Cargo.toml
crates/sail-spark-connect/src/proto/data_type_arrow.rs
crates/sail-spark-connect/src/session_manager.rs

This PR ensures the Parquet INT96 data type is read as timestamp with microsecond precision.
Note that this does not reach full parity with the Spark data reader yet. We need to convert NTZ timestamp to LTZ and respect `org.apache.spark.sql.parquet.row.metadata`. This will be future work.

Read Parquet INT96 with the correct time unit

---

crates/sail-common/src/config/application.yaml

Try to align configs with the closest matching Spark config.
https://spark.apache.org/docs/latest/configuration.html

chore: tweak cluster timeout configs

---

.github/workflows/release.yml
README.md
docker/quickstart/Dockerfile
docs/guide/integrations/mcp-server.md
docs/introduction/getting-started/index.md
pyproject.toml

This breaking change removes the `spark` optional dependencies (aka "extra") in the PySail Python package so that the user can choose the PySpark version for their installation.

chore!: remove `spark` extra for Python

---

crates/sail-plan/src/function/scalar/datetime.rs
crates/sail-spark-connect/tests/gold_data/function/datetime.json

Support dayname function for feature parity with spark 4.0.0
https://spark.apache.org/docs/latest/api/sql/index.html#dayname
Part of #557

feat: dayname function

---

crates/sail-plan/src/function/scalar/conditional.rs
crates/sail-spark-connect/tests/gold_data/function/conditional.json

Support zeroifnull and nullifzero functions for feature parity with spark 4.0.0
https://spark.apache.org/docs/latest/api/sql/index.html#nullifzero
https://spark.apache.org/docs/latest/api/sql/index.html#zeroifnull
Part of #557

feat: add zeroifnull and nullifzero functions

---

Cargo.lock
crates/sail-plan/src/resolver/option.rs
crates/sail-plan/src/resolver/plan.rs

As discussed offline, this PR provides a temporary, quick-and-dirty fix by reverting to some previous logic.
A proper fix will be implemented in https://github.com/lakehq/sail/pull/592

fix: temp fix for resolve options for external table create

---

crates/sail-plan/src/function/scalar/array.rs

array_position:
1) return NULL only if input array is NULL
otherwise, if element not found, return 0
2) Fix panic on empty array
```python
import pyspark.sql.functions as F
server.start()
port = 50051
from pyspark.sql import functions as sf
from pyspark.sql.types import ArrayType, StringType, StructField, StructType
schema = StructType([StructField("data", ArrayType(StringType()), True)])
df = spark.createDataFrame([
(["a", "c"],), (["c"],), ([None],), (None,), 
], schema=schema)
df.createOrReplaceTempView("v1") …
```

fix: array_position inconsistent result and internal_error in some cases

---

crates/sail-plan/src/function/scalar/array.rs

array_append and array_prepend now return NULL if input array is NULL, like in spark
```python
server.start()
from pyspark.sql import functions as sf
from pyspark.sql.types import ArrayType, IntegerType, StructType, StructField
schema = StructType([
StructField("data", ArrayType(IntegerType()), True)
])
df = spark.createDataFrame([(None,)], schema=schema)
df.select(sf.array_append(df.data, 4)).show()
df.select(sf.array_prepend(df.data, 4)).show()
```
```
+---------------------+
|array_append(data, 4)| …
```

fix: array_append and array_prepend inconsistent NULL behaviour

---

crates/sail-plan/src/function/aggregate.rs

now all nulls are removed from result list, like in spark:
```python
server.start()
from pyspark.sql import functions as sf
df = spark.createDataFrame([[1],[None],[2]], ["c"])
df.agg(sf.sort_array(sf.array_agg('c')).alias('sorted_list')).show()
df = spark.createDataFrame([[None],[None],[None]], "c int")
df.agg(sf.sort_array(sf.array_agg('c')).alias('sorted_list')).show()
```
```
+-----------+
|sorted_list|
+-----------+
|     [1, 2]|
+-----------+
+-----------+
|sorted_list|
+-----------+
|         []| …
```

fix: array_agg null values treatment

---

crates/sail-plan/src/function/aggregate.rs

Found out that some of my solutions are sub-optimal and can be rewritten without external function calls:
`collect_set` is `array_agg_udaf` with `distinct` and `ignore_nulls` required
`array_agg` is `array_agg_udaf` with `ignore_nulls` required
array_distinct and array_remove that could slow down the queries on big arrays are not needed anymore
Behaviour is not changed, tests are still passed

perf: collect_set and array_agg functions

---

crates/sail-plan/src/function/scalar/array.rs

return NULL if any of sub-arrays is NULL like spark does
```python
server.start()
spark.sql("""SELECT flatten(array(null, array(1, 2), array(3, 4)))""").show()
```
```
+----------------------------------------------+
|flatten(array(NULL, array(1, 2), array(3, 4)))|
+----------------------------------------------+
|                                          NULL|
+----------------------------------------------+
```
closes #641

fix: flatten function inconsistent null behaviour

---

crates/sail-plan/src/function/common.rs
crates/sail-plan/src/function/scalar/array.rs
crates/sail-spark-connect/tests/gold_data/function/array.json

Add `array_insert` function implementation:
https://spark.apache.org/docs/latest/api/sql/index.html#array_insert
using only datafusion expressions
passes spark-tests
please tell if there is duplicate expression elimination in Sail, because the plan creates a lot of them
raises exception if position is zero, like spark does
but the exception message is not informative in this case
because cannot override datafusion runtime exceptions at the plan level
so I just found some datafusion method that is always raising exception and call it in case of 0
part of #220

feat: add array_insert function

---

crates/sail-plan/src/extension/function/collection/spark_concat.rs

fix concat behaviour for various types:
binary -> binary (casts to strings and uses string concat but casts result to binary)
primitive (coerce to string) -> string 
string and primitive -> string
any NULL input -> NULL output
passes spark-tests
closes #646 (if it's ok to create another issue about passing input arrays with different but coercible types)

fix: concat function behaviour on some subset of input types

---

crates/sail-plan/src/formatter.rs

rename output column names for spark functions
confirms correct results for some functions implemented earlier
for other functions reveals new errors which were obfuscated by naming problem
closes #602

fix: column output naming

---

crates/sail-execution/proto/sail/plan/physical.proto
crates/sail-execution/src/codec.rs
crates/sail-plan/src/extension/function/datetime/mod.rs
crates/sail-plan/src/extension/function/datetime/spark_from_to_utc_timestamp.rs
crates/sail-plan/src/function/scalar/datetime.rs
crates/sail-spark-connect/tests/gold_data/function/datetime.json

implement `to_utc_timestamp` function 
https://spark.apache.org/docs/latest/api/sql/index.html#to_utc_timestamp
reuse `from_utc_timestamp` code
rename the class and refactor error checks
no logic duplication
part of #505

feat: to_utc_timestamp function

---

crates/sail-common/src/spec/expression.rs
crates/sail-plan/src/resolver/expression.rs
crates/sail-spark-connect/src/proto/expression.rs
crates/sail-spark-connect/tests/gold_data/expression/cast.json
crates/sail-spark-connect/tests/gold_data/plan/plan_select.json
crates/sail-sql-analyzer/src/expression.rs

implement `try_cast` column method:
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Column.try_cast.html#pyspark.sql.Column.try_cast
the overriden cast cases need to be further checked for correctness in terms of try_cast and adjusted accordingly
but it passes the spark-test, so basic functionality is provided

feat: try_cast column method

---

docs/.vitepress/theme/app.css
docs/development/recipes/object-store.md
docs/guide/storage/azure.md
docs/guide/storage/gcs.md
docs/guide/storage/index.md
docs/guide/storage/memory.md
docs/guide/storage/s3.md

1. Add configuration docs for Azure and GCS. This is mostly from the object_store documentation.
2. Improve the URL format docs for S3 and Azure. Similar code examples are removed, so that the reader can get the high-level idea more easily.
This PR also fixes the dark mode issue (possibly due to previous major version upgrades of the dependencies).

docs: update storage guide

---

crates/sail-common-datafusion/src/utils.rs
crates/sail-plan/src/resolver/command/insert.rs
crates/sail-plan/src/resolver/command/write.rs
crates/sail-plan/src/resolver/command/write_v1.rs
crates/sail-plan/src/resolver/command/write_v2.rs
crates/sail-plan/src/resolver/expression.rs

The write plan resolver incorrectly uses the input schema instead of the table schema to resolve overwrite conditions (used for the `INSERT ... REPLACE WHERE ...` SQL statement and the `.overwrite()` method for the v2 writer API). This PR fixes this issue.
I tried the following example after this fix:
```python
spark.sql(f"CREATE OR REPLACE TABLE foo (id INT, name STRING) USING DELTA")
spark.sql(f"""
INSERT INTO TABLE foo
REPLACE WHERE name = 'A'
SELECT * FROM VALUES (5, 'A'), (6, 'A')
""")
```
The server now returns the following error, which is expected:
```text
pyspark.errors.exceptions.connect.UnsupportedOperationException: unsupported sink mode for Delta: OverwriteIf { condition: BinaryExpr { left: Column { name: "name", index: 1 }, op: Eq, right: Literal { value: Utf8("A"), field: …
```

fix: resolver logic for overwrite conditions

---

crates/sail-execution/src/codec.rs
crates/sail-plan/src/extension/function/datetime/mod.rs
crates/sail-plan/src/extension/function/datetime/spark_to_chrono_fmt.rs
crates/sail-plan/src/formatter.rs
crates/sail-plan/src/function/scalar/datetime.rs
crates/sail-spark-connect/tests/gold_data/function/datetime.json

implement spark_to_chrono_fmt func as UDF(column)
instead of parsing ScalarValue to str on planner side
implement to_unix_timestamp function:
https://spark.apache.org/docs/latest/api/sql/index.html#to_unix_timestamp
part of #505

feat: spark_to_chrono_fmt and to_unix_timestamp funcs

---

Cargo.lock
crates/sail-data-source/src/options/resolver.rs
python/pysail/tests/spark/test_parquet.py
python/pysail/tests/spark/utils.py

This fixes #718.
The problem became obvious when I used the tool to inspect Parquet data file content: `pqrs schema --detailed <path>`. The large file size is due to the bloom filter for each column.
It turns out that the Parquet writer enables bloom filter when related options (FPP or NDV) are set, even if the bloom filter is not explicitly enabled. This is documented in `properties.rs` in the `parquet` crate but this information is hard to find.
This PR adjusted our configuration processing logic to make sure the bloom filter is turned off on write by default.

fix: turn off bloom filter for Parquet write by default

---

crates/sail-plan/src/resolver/plan.rs

provide support for NaN values in VALUES like in spark
```python
import pyspark.sql.functions as F
server.start()
print(port)
spark.sql("select * from values (NULL), (DOUBLE('NAN')), (1.5f)").toArrow()
spark.sql("select * from values (NULL), (FLOAT('NAN')), (1.5)").toArrow()
spark.sql("select * from values (NULL), (FLOAT('NAN')), (1.5f)").toArrow()
spark.sql("select * from values (NULL), (DOUBLE('NAN')), (cast(1 as long))").toArrow()
spark.sql("select * from values (NULL), (FLOAT('NAN')), (cast(1000000005 as …
```

fix: from values containing NaN cast error

---

crates/sail-catalog/src/command.rs

According to the Spark documentation, `pyspark.sql.Catalog.getTable()` should return tables, views, or temporary views. This PR fixes the catalog command to make it adhere to this behavior.
This also fixes the issue with the `describe_view` MCP tool.

fix: catalog get table command

---

crates/sail-common/src/config/application.yaml
docs/.vitepress/theme/layouts/MainLayout.vue
docs/introduction/getting-started/index.md

1. Change default session timeout to 15 minutes and add docs. This is based on user feedback in #736 and #747.
2. Update the docs about `pyspark-client`. This is based on user feedback for <https://github.com/mwc360/LakeBench/pull/37#issuecomment-3183968000>.
3. Add banner for merch.

fix: adjust default session timeout and update docs

---

crates/sail-plan/src/extension/function/map/map_function.rs
crates/sail-plan/src/function/common.rs
crates/sail-plan/src/function/scalar/map.rs
crates/sail-spark-connect/tests/gold_data/function/map.json

implement `map_from_entries`
https://spark.apache.org/docs/latest/api/sql/index.html#map_from_entries
unify all ways to create a map in MapFunction:
- `map(k1,v1,k2,v2,..)`  (now done with some additional lightweight expression logic)
- `map_from_arrays`
- `map_from_entries`
remove usage of datafusion `map_udf` because it is not consistent with spark in many ways
all types of keys and values are coerced with datafusion `make_array` logic which works well for spark-tests
no more need to implicitly cast anything
now all maps are deduplicated on creation
and the code can be easily adjusted to change behavior when spark config will be implemented
closes #667
part of #307

feat: map_from_entries, unify all ways to create a map in MapFunction

---

crates/sail-plan/src/function/scalar/map.rs
crates/sail-spark-connect/tests/gold_data/function/map.json

implement `map_concat` function:
https://spark.apache.org/docs/latest/api/sql/index.html#map_concat
supports type coersion for concatenated keys and values
`map(k, v)` improvements:
- return readable error when called with odd number of args instead of panic
- simplify args to key-value pairs transform
part of #307

feat: map_concat func, args check for map(k, v) func

---

crates/sail-plan/src/error.rs
crates/sail-plan/src/function/common.rs
crates/sail-plan/src/function/scalar/array.rs
crates/sail-plan/src/function/scalar/collection.rs

introduced `IntoPlanResult` trait and added logic to ScalarFunctionBuilder
now it is possible to use `unary`, `binary`, `ternary` etc. with functions that return PlanResult but not use function_context
this is most useful for using `when.when...end()` which returns Result instead of Expr
more clean than turning to `custom`
see `F::ternary(array_insert)` and `F::binary(sort_array)` for example
removed unnesessary boilerplate without logic change
replaced handwritten`udf_expr` to builtin `ScalarUDF::from(RaiseError::new()).call(args)` functionality

chore: refactor array and collection modules

---

crates/sail-execution/src/codec.rs
crates/sail-plan/src/extension/function/map/map_function.rs
crates/sail-plan/src/extension/function/map/mod.rs
crates/sail-plan/src/extension/function/map/str_to_map.rs
crates/sail-plan/src/function/scalar/map.rs
crates/sail-spark-connect/tests/gold_data/function/map.json

implements `str_to_map`:
https://spark.apache.org/docs/latest/api/sql/index.html#str_to_map
reuse existing low-level functions:
- `spark_split_inner` (split input to pairs)
- `split_to_array` (split pairs to key-value elements)
- `map_from_arrays_inner` (create result Map)
closes #307

feat: str_to_map function

---

crates/sail-plan/src/formatter.rs
crates/sail-plan/src/function/scalar/string.rs
crates/sail-spark-connect/tests/gold_data/function/string.json

`position` and `locate` functions now support third argument 
which is start 1-based position to search substring:
```
> SELECT position('bar', 'foobarbar', 5);
7
```
https://spark.apache.org/docs/latest/api/sql/index.html#position
https://spark.apache.org/docs/latest/api/sql/index.html#locate
part of #508

fix: position and locate funcs with startpos arg

---

crates/sail-plan/src/formatter.rs
crates/sail-plan/src/function/scalar/string.rs
crates/sail-plan/src/utils.rs
crates/sail-spark-connect/tests/gold_data/function/string.json

feat:
implement `regex_instr` function using datafusion udf:
https://spark.apache.org/docs/latest/api/sql/index.html#regexp_instr
fix:
type casting for multiple string functions
now most of the casting is regulated by `cast_to_logical_string_or_try` func
turned functions using that func to `custom` because they now need `schema` for type coersion
(maybe some are left without proper coersion, needs to be further checked)
chore:
introduce helper functions for boilerplate that is used three times or more
remove overrides for DataFusion 43.0.0 bug
it seems casting of scalars is fully supported now
and some functions called with some input types don't need casting at all
code for vararg functions is now unified by popping last argument and taking other with .two() of .three() without cloning …

feat: regex_instr,  fix: string funcs type casting, chore: string funcs refactoring

---

crates/sail-function/src/scalar/map/map_from_entries.rs
crates/sail-function/src/scalar/map/utils.rs
python/pysail/tests/spark/function/test_map_from_entries.txt

map_from_entries now returns NULL for the row if any entry in list is null:
(was failing)
```python
import pyspark.sql.functions as F
server.start()
#spark = SparkSession.builder.appName("test").master("local[4]").getOrCreate()
spark.sql("""
SELECT map_from_entries(data) as result, typeof(map_from_entries(data)) as type
from values
(array(
struct(1 as a, "a" as b), 
cast(NULL as struct<a: int, b: string>), 
cast(NULL as struct<a: int, b: string>)
)),
(NULL),
(array(
struct(2 as a, "b" as b), 
struct(3 as a, "c" as b)
)),
(array(
struct(4 as a, "d" as b),
cast(NULL as …
```

fix: map_from_entries error on lists with null entries

---

crates/sail-cache/src/file_metadata_cache.rs
crates/sail-cache/src/lib.rs
crates/sail-common/src/config/application.rs
crates/sail-common/src/config/application.yaml
crates/sail-spark-connect/src/session_manager.rs

Closes #516.
This is a follow-up of #687.
Note: `parquet.cache_metadata` is removed in <https://github.com/apache/datafusion/pull/17062> so we can no longer configure metadata cache for each data source.

feat: file metadata cache for Parquet

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
crates/sail-cli/Cargo.toml
docs/reference/changelog/index.md
pyproject.toml
python/pysail/__init__.py

* Upgrade `aws-lc-rs` to 1.14.1 since 1.14.0 has a bug for cross-compilation.
* Use `macos-15-intel` for macOS x86 build since `macos-13` will be discontinued soon.

chore: prepare v0.3.6
